#nom de classe, nom du module liste d'args

retrieval:
  db:
    class_name: ChromaRetrieval
    module_name: yololo.retrieval.chroma_retrieval
    args:
      persist_directory: ./chroma_db
  search:
    class_name: TavilyRetrieval
    module_name: yololo.retrieval.search_retrieval
    args:
      api_key: ${TAVILY_API_KEY}
      max_results: 5

models:
  gpt-4o-mini:
    class_name: OpenaiApi
    module_name: yololo.llm.openai_api
    args:
      model_id: gpt-4o-mini
  qwen-0.6b:
    class_name: HuggingFaceModel
    module_name: yololo.llm.hf
    args:
      model_id: Qwen/Qwen3-0.6B-Base
  qwen-4b:
    class_name: HuggingFaceModel
    module_name: yololo.llm.hf
    args:
      model_id: Qwen/Qwen-4B
  gemini-2.5-flash:
    class_name: GeminiApi
    module_name: yololo.llm.gemini_api
    args:
      model_id: gemini-2.5-flash